<?php

/**
 * @file
 * Contains install-time code for the CiviCRM module.
 */

/**
 * Implements hook_install().
 *
 * Contains things that need to be installed when the module is installed.
 */
function civicrm_install() {
  /** @var \Civi\Setup $setup */
  $setup = _civicrm_setup();

  if ($setup->getPendingAction() !== NULL) {
    // Ex: If you do an advanced installation with `cv core:install`, then
    // `hook_install` shouldn't activate the default/unconfigured install.
    return;
  }

  $installed = $setup->checkInstalled();
  if ($installed->isDatabaseInstalled()) {
    throw new \Exception("CiviCRM appears to have already been installed. Skipping full installation.");
  }
  if ($installed->isSettingInstalled()) {
    $setup->getModel()->setValues(['doNotCreateSettingsFile' => TRUE]);
  }

  $setup->installFiles();
  $setup->installDatabase();
}

/**
 * Implements hook_uninstall().
 */
function civicrm_uninstall() {
  /** @var \Civi\Setup $setup */
  $setup = _civicrm_setup();

  $setup->uninstallFiles();
  $setup->uninstallDatabase();
}

/**
 * @return \Civi\Setup
 */
function _civicrm_setup() {
  if (defined('CIVI_SETUP')) {
    return Civi\Setup::instance();
  }

  $civicrm_base = _civicrm_find_civicrm();
  require_once $civicrm_base . '/CRM/Core/ClassLoader.php';
  CRM_Core_ClassLoader::singleton()->register();

  \Civi\Setup::assertProtocolCompatibility(1.0);
  \Civi\Setup::init([
    'cms' => 'Drupal8',
    'srcPath' => $civicrm_base,
  ]);

  return Civi\Setup::instance();
}

/**
 * Returns the path to where CiviCRM is installed.
 *
 * Installation via composer is recommended. We also allow /modules/civicrm,
 * which seems to work fine.
 *
 * @return string|null
 *   A string to the location if we can find where CiviCRM is installed, NULL
 *   if we can't.
 */
function _civicrm_find_civicrm() {
  // TODO: This works with standard composer layouts but would be easy to break
  // via installer-paths. However, it should be possible to replace this - since we
  // can count on composer's autoloader being setup already. Some ideas:
  //  - Use ReflectionClass('Civi') to find the path
  //  - Update `Civi.php` to provide a function with its __DIR__

  $possible_paths = [];

  if ($path = \Drupal::service('extension.list.module')->getPath('civicrm')) {
    $possible_paths[] = $path;
  }
  $possible_paths[] = 'vendor/civicrm/civicrm-core';
  $possible_paths[] = '../vendor/civicrm/civicrm-core';

  foreach ($possible_paths as $path) {
    if (file_exists($path . '/CRM/Core/ClassLoader.php')) {
      return \Drupal::service('file_system')->realpath($path);
    }
  }

  return NULL;
}
